### ISSUE TITLE
the pretrain file can not work

### ISSUE THREAD

**Issue by shaowang3194** [hyunnamlee/RAPUNet#3]
when I use your H5 file to test the data,I met this error and the version of the enviroment completely follow the README

Traceback (most recent call last):
  File "F:\virtualC\RAPUNet-main\test2.py", line 49, in <module>
    model = keras.models.load_model(r"D:\RAPUNet_Kvasir.h5", custom_objects={'dice_metric_loss': dice_metric_loss})
  File "D:\Anaconda3\envs\duck\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "D:\Anaconda3\envs\duck\lib\site-packages\keras\utils\generic_utils.py", line 605, in class_and_config_for_serialized_keras_object
    raise ValueError(
ValueError: Unknown layer: nfnets>ZeroInitGain. Please ensure this object is passed to the `custom_objects` argument. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.

**Comment by hyunnamlee** [comment]
Hello shaowang3194

Actually, I’m not sure the reason of the error. I’ll try to find the clue and If I find it, inform you. 
Have a nice day!!

**Comment by shaowang3194** [comment]
Thank you for the reply.
